### PR TITLE
Implement pass-through callbacks (fix for #11)

### LINKED ISSUE #11: Dump response as it goes back
I didn't find a good title, but an example will be better. I've written this article based on https://github.com/adoy/PHP-FastCGI-Client/ (that you've used to build this very project): https://www.dugwood.com/949904-php5-opcode-caching-and-memory-storage-with-apc-xcache-in-command-line-interface-cli-or-cron.html

The important part here is the client call:
`$response = $client->request($request, null, create_function('$response', 'echo $response;'));`

Here, every time the client receives a packet, it will send it to the function (here it's a simple `echo()`). It may be strange, as most of the people just want the answer from a PHP script, but I use it to access APCu's cache, and even OpCache for performance. So I run a lot of batch scripts with it, with took a long time to process, and I want to see the result as soon as the main PHP script `echo()` something.

I could write to a log, and on the main call read this log, but that's really not efficient I think. The best way to handle this would be to fire `readResponse()` (https://github.com/hollodotme/fast-cgi-client/blob/master/src/Client.php#L115) each time a packet arrives.

I use a function named `show()` to force the PHP-FPM to send the message I want:
```php
class FastCGI_Controller
{
	private static $buffering = 4096;

	static public function init()
	{
		self::$buffering = (int) ini_get('output_buffering');
	}

	static public function show($string)
	{
		echo str_repeat("\033[0m", max(1, ceil((self::$buffering - strlen($string) % self::$buffering) / 4))).$string;
		flush();
	}
}
```

So in the main PHP script (called within PHP-FPM), I'll send some `FastCGI_Controller::show('task 1: completed'.PHP_EOL);`, and my PHP caller script will dump it immediately in my console (or cron log).

Maybe it's better to handle this another way, but so far I didn't think it through. Perhaps you'll have another idea to make this work.

Of course I can code it, and send a PR when done, but I need your input first :-)

### PR DESCRIPTION
**Pull request by dugwood**
Implemented in 1.x-stable only, I don't have PHP 7.1 to test the branch on master. Fixes #11.

Added 2 tests to check if it worked well.

Must add that PHP-FPM will return the echo'ed text as soon as it goes over the limit of `output_buffering`.

### CODE REVIEW

**Comment by dugwood** [comment]
Please note that I've also changed: https://github.com/hollodotme/fast-cgi-client/blob/1.x-stable/src/Socket.php#L280 => now both `case` end up in the same common code.

**Comment by dugwood** [comment]
Oh and I definitely need to add some explanation on the README page. Will do in another PR if okay for you!

**Comment by hollodotme** [comment]
Please add the documentation to README.md in this PR too, because the docs are part of the feature.

**Comment by dugwood** [comment]
I've added the example script in the README, but didn't add any version release, as I don't know if it will be part of the next minor release or not.

For the `master` branch, I could do a diff with the `1.x-stable` branch, when you've merged the PR.

**Comment by dugwood** [comment]
Thanks!

**Pull request merged**
